[package]
name = "rilo"
version = "0.1.0"
authors = ["Ole Ravna <olevra@stud.ntnu.no>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
termios="0.3.1"
ascii="0.7"
scan_fmt = "0.2.4"
